version: '3'
services:
  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
