spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create
